#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run typecheck
echo "🔍 Running TypeScript type check..."
yarn typecheck

# Run biome format and check
echo "🎨 Running Biome format and check..."
yarn check:unsafe
